# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 426ce1c4ef0711abd866a50d8e554278f461535dc616d156017736342db9c9ce18372e049d150f8ad4709ba9fb584b490596308304067331620b4442216812f7

test:
  secret_key_base: 14900763bcfaea3db4de0bf5effec05e35074f5b58c08de8294c9026690692ca5a3c767535a722849f0680f3467dbe50af0fd01d5f4feaffaf5dd83a47faff93

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
