# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 28f6ada2c2515c860a77b8d84f7c9df2b8b9fcb46b9a759ef78a81bc803f50bd3a5b7d7a2916e4d73228a556438d6848baa3609b2dbae3d53358eaf6cb9800bf

test:
  secret_key_base: f691e4889791cd1107289514794241c66977ea0fde0c6898167a270bed058eafc5eb61544ac087416677ed0231cf64f0218f5afc0f6d13dde611fa2229f31de8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
